# Generated by Django 3.2.6 on 2021-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='alexa_rank',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='websitecategory',
            name='count',
            field=models.IntegerField(default=None),
        ),
    ]
